/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_bringardner_fsh_NativeKeyboard */

#ifndef _Included_us_bringardner_fsh_NativeKeyboard
#define _Included_us_bringardner_fsh_NativeKeyboard
#ifdef __cplusplus
extern "C" {
#endif
#undef us_bringardner_fsh_NativeKeyboard_MAX_SKIP_BUFFER_SIZE
#define us_bringardner_fsh_NativeKeyboard_MAX_SKIP_BUFFER_SIZE 2048L
#undef us_bringardner_fsh_NativeKeyboard_DEFAULT_BUFFER_SIZE
#define us_bringardner_fsh_NativeKeyboard_DEFAULT_BUFFER_SIZE 16384L
#undef us_bringardner_fsh_NativeKeyboard_MAX_BUFFER_SIZE
#define us_bringardner_fsh_NativeKeyboard_MAX_BUFFER_SIZE 2147483639L
#undef us_bringardner_fsh_NativeKeyboard_KEY_INTR
#define us_bringardner_fsh_NativeKeyboard_KEY_INTR -3L
#undef us_bringardner_fsh_NativeKeyboard_CTRL_C
#define us_bringardner_fsh_NativeKeyboard_CTRL_C 3L
#undef us_bringardner_fsh_NativeKeyboard_CTRL_Z
#define us_bringardner_fsh_NativeKeyboard_CTRL_Z 26L
#undef us_bringardner_fsh_NativeKeyboard_CTRL_BACKSLASH
#define us_bringardner_fsh_NativeKeyboard_CTRL_BACKSLASH 28L
#undef us_bringardner_fsh_NativeKeyboard_KEY_EOF
#define us_bringardner_fsh_NativeKeyboard_KEY_EOF -1L
#undef us_bringardner_fsh_NativeKeyboard_KEY_NONE
#define us_bringardner_fsh_NativeKeyboard_KEY_NONE -2L
#undef us_bringardner_fsh_NativeKeyboard_CTRL_D
#define us_bringardner_fsh_NativeKeyboard_CTRL_D 4L
#undef us_bringardner_fsh_NativeKeyboard_UP
#define us_bringardner_fsh_NativeKeyboard_UP 500L
#undef us_bringardner_fsh_NativeKeyboard_DN
#define us_bringardner_fsh_NativeKeyboard_DN 501L
#undef us_bringardner_fsh_NativeKeyboard_RT
#define us_bringardner_fsh_NativeKeyboard_RT 502L
#undef us_bringardner_fsh_NativeKeyboard_LF
#define us_bringardner_fsh_NativeKeyboard_LF 503L
#undef us_bringardner_fsh_NativeKeyboard_HOME
#define us_bringardner_fsh_NativeKeyboard_HOME 504L
#undef us_bringardner_fsh_NativeKeyboard_PAGE_UP
#define us_bringardner_fsh_NativeKeyboard_PAGE_UP 505L
#undef us_bringardner_fsh_NativeKeyboard_PAGE_DOWN
#define us_bringardner_fsh_NativeKeyboard_PAGE_DOWN 506L
#undef us_bringardner_fsh_NativeKeyboard_DELETE
#define us_bringardner_fsh_NativeKeyboard_DELETE 507L
#undef us_bringardner_fsh_NativeKeyboard_END
#define us_bringardner_fsh_NativeKeyboard_END 508L
/*
 * Class:     us_bringardner_fsh_NativeKeyboard
 * Method:    getChar
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_us_bringardner_fsh_NativeKeyboard_getChar
  (JNIEnv *, jobject);

/*
 * Class:     us_bringardner_fsh_NativeKeyboard
 * Method:    ready
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_us_bringardner_fsh_NativeKeyboard_ready
  (JNIEnv *, jobject);

/*
 * Class:     us_bringardner_fsh_NativeKeyboard
 * Method:    setSignalKeys
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_us_bringardner_fsh_NativeKeyboard_setSignalKeys
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     us_bringardner_fsh_NativeKeyboard
 * Method:    setProgramMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_us_bringardner_fsh_NativeKeyboard_setProgramMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     us_bringardner_fsh_NativeKeyboard
 * Method:    isTerminal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_us_bringardner_fsh_NativeKeyboard_isTerminal
  (JNIEnv *, jobject);

/*
 * Class:     us_bringardner_fsh_NativeKeyboard
 * Method:    giveTerminalTo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_us_bringardner_fsh_NativeKeyboard_giveTerminalTo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     us_bringardner_fsh_NativeKeyboard
 * Method:    setProcessGroup
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_us_bringardner_fsh_NativeKeyboard_setProcessGroup
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     us_bringardner_fsh_NativeKeyboard
 * Method:    stoppedBy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_us_bringardner_fsh_NativeKeyboard_stoppedBy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
